### ISSUE TITLE
Text is pushed off screen when 7 or more seals are gathered

### ISSUE THREAD

**Issue by Enzemo** [MidoriKami/EzWondrousTails#1]
The text will display but rapidly scrolls off the screen, i've tried to catch it on a screenshot for you; it falls very fast

![image](https://user-images.githubusercontent.com/11069930/115068025-95a32e00-9ee9-11eb-9610-ba65ddd306f9.png)

**Comment by daemitus** [comment]
You got that by using the repo? I haven't seen that bug in a while

**Comment by Enzemo** [comment]
Yep, using your repo. Happy to give any extra info if you need logs or
anything
Edit: Just to clarify: https://github.com/daemitus/MyDalamudPlugins/raw/master/pluginmaster.json

**Comment by daemitus** [comment]
Nah, I know where it's coming from, just a matter of fixing it again

**Comment by daemitus** [comment]
my repo is now at 2.0.0.0, please try again and let me know if the issue persists.
