### ISSUE TITLE
Duty Finder not opening when clicking on WT duty icons

### ISSUE THREAD

**Issue by pksage** [MidoriKami/EzWondrousTails#14]
My comment from the Dalamud Discord:

> Re: clicking on the icons in WT to open the duty finder to the appropriate spot:
> 
> I pulled down DailyDuty and built from source, then made sure to enable the WT module, but still not getting anything when clicking an icon. The debug window shows the duties mapped appropriately.
> 
> I've been digging into this as an experienced programmer, but one who's new to Dalamud plugins. Is this line where it's supposed to be opening Duty Finder, or is that somewhere else? https://github.com/MidoriKami/EzWondrousTails/blob/master/WondrousTailsSolver/WondrousTailsSolverPlugin.cs#L142
> My assumption is that lines 83-85 are registering AddonDutyReceiveEventDetour() as a listener to clicks on the WT duty icons, and while AddonSetupDetour() is firing for me without errors, AddonDutyReceiveEventDetour() is not firing at all

**Comment by MidoriKami** [comment]
I need to reinspect how Dae originally hooked the events here, as he did something really clever by hooking a very specific part of the components children to receive events for just that node.

Alternative approach might be to use AddonEventManager from Dalamud to add custom events that trigger on click. Requires more thought before implementation.

**Comment by MidoriKami** [comment]
Fixed in 9005e73adfc0e1225333f6d352a2d56b0d416410
