### ISSUE TITLE
"Current Duty" frame wrong size

### ISSUE THREAD

**Issue by katawajojo** [MidoriKami/EzWondrousTails#17]
Currently, the "Current Duty" overlay is incorrectly scaled.
It looks to be utilizing the entire texture instead of just the specific frame region.

![image](https://github.com/user-attachments/assets/b2b6a3d2-a34f-4416-ba07-ff734744de47)

**Comment by MidoriKami** [comment]
Ah I changed how I manage UI texture resolution setting in KamiToolKit, easy fix, thanks for reporting this issue.

**Comment by MidoriKami** [comment]
Fixed in 036a34e0d4cdcd1d1c04867ac550798de0ebbb52

**Comment by katawajojo** [comment]
It looks like it actually got worse unfortunately.

![image](https://github.com/user-attachments/assets/44b7ee8c-fba9-46f3-8b62-c148fdb3ed7a)

**Comment by MidoriKami** [comment]
Oops. Thanks for letting me know.

I'm not currently subbed so my only testing account is a lvl 50 free trial account. Makes it hard to test without spending lots of time I don't have progressing the story.
