### ISSUE TITLE
New Categories don't open Duty Finder

### ISSUE THREAD

**Issue by ArynBlack** [MidoriKami/EzWondrousTails#18]
Hello! Thank you for the work on your amazing plugin, but I believe that the changed to the names of some of the categories and the reorganization of others currently causes an issue with popping up the duty finder with the aforementioned category of duties. Examples include Leveling Dungeons (Lv. 1-49) High-level Dungeons (Lv. 70-80) and High-level Dungeons (Lv. 90) back from patch 7.1

There may be others but I have not run across them just yet in my current WT book.

**Comment by MidoriKami** [comment]
Your phrasing is somewhat confusing to me.

It's known that any *new* duties won't trigger the duty finder to open, I will need a community contribution to the task list to be able to support new entries.

Entries from **7.0** should still work however.

**Comment by MidoriKami** [comment]
So it seems square added a bunch of new categories this time around, as I am not actively playing, I have no reasonable way to test and verify changes/fixes.

I would greatly appreciate a PR to https://github.com/MidoriKami/KamiLib/blob/master/Classes/WondrousTailsTaskResolver.cs , to correct any errors and to add new entries.

**Comment by MidoriKami** [comment]
Feature is being removed.

**Comment by Shiichibukai** [comment]
Ugh, couldve just left it as is till someone PR'd the changes. I dont understand the need to remove useful features as long as it works for most things. Or drop a testing build somewhere. 

Frustrating to say the least.
