### ISSUE TITLE
Crashes sometimes, haven't been able to figure out a trend when

### ISSUE THREAD

**Issue by ibigfire** [MidoriKami/EzWondrousTails#2]
Sometimes when I open the Wondrous Tails journal the game crashes, though I haven't been able to figure out a trend it's happened twice.  This most recent time it happened it occurred just after I'd finished a dungeon that earned me a stamp, and I tried to open the Wondrous Tails book to tick it before I left the dungeon.

Not sure if I can make it consistently crash via doing that same thing again or not yet.

**Comment by daemitus** [comment]
Are you using the version off my personal repo? I have a pending PR for the main repo currently that hopefully fixes that. The latest is v2.0.

**Comment by ibigfire** [comment]
Ah, nope, I'm using the main repo I assume.  Just the one that shows up in the default list of plugins when using quicklauncher.  Happy to know a fix is in the pipeline!  I'll go ahead and close this then, thanks very much for making this.  ^_^
