### ISSUE TITLE
Open DF?

### ISSUE THREAD

**Issue by amaraame** [MidoriKami/EzWondrousTails#20]
I had a plugin that opened DF from the WT journal. I thought it was this one. it doesn't seem to do that any more. if i have the wrong plugin in mind, do you happen to know which one i'm thinking of? thank you.

**Comment by princessoak** [comment]
It was this one. For some reason they just removed the feature. Unfortunate rly, it was one of the best features.

**Comment by princessoak** [comment]
Well actually it may have been another plugin by this author, EzWondrousTails(?) — not sure. Either way, feature was removed I think 2 days ago

**Comment by amaraame** [comment]
that's lame. it was pretty much the sole reason i used this. tyvm
