### ISSUE TITLE
Opens the corresponding duty

### ISSUE THREAD

**Issue by New3Darot** [MidoriKami/EzWondrousTails#21]
Hi, this is not exactly an issue, but can you implement again the function that opens the corresponding duty when clicking on the journal? It was damn convenient!

In any case, great work, both for this plugin and all the others!
Thanx

**Comment by MidoriKami** [comment]
No. That feature was intentionally removed. 

Blame Square Enix for completely changing how it works every single patch. I am tired of having to redesign my systems every patch.
