### ISSUE TITLE
Incorrect results / not working v2.1.1.0

### ISSUE THREAD

**Issue by bdew** [MidoriKami/EzWondrousTails#3]
After last update my WT shows incorrect chances (3 lines is impossible in this config?)

![image](https://user-images.githubusercontent.com/96327/152506123-f575a6b3-ebaa-4f83-b4cd-aabc36f2f4b7.png)

Closing and reopening the window the plugin just stops showing until i restart it

![image](https://user-images.githubusercontent.com/96327/152506143-6349eae5-b5a7-45c9-aef2-5a62853ee41d.png)

going back to 2.1.0.3 it works correctly

**Comment by daemitus** [comment]
:( ok ill take a look at whats going on

**Comment by daemitus** [comment]
OH i know what i did. ok, I just need to revert some things.

**Comment by daemitus** [comment]
ok. new version coming down the pipe. re-open/make a new one if you still see issues please.
