### ISSUE TITLE
Could not install version 2.1.1.1

### ISSUE THREAD

**Issue by ha-ku** [MidoriKami/EzWondrousTails#4]
`/xllog` shows something like this
![image](https://user-images.githubusercontent.com/18721230/152630763-54a3df11-cd8c-43b7-8387-49af59c42fac.png)

**Comment by daemitus** [comment]
The current version of dalamud is 6.3.0.2. Upgrade.

**Comment by ha-ku** [comment]
> The current version of dalamud is 6.3.0.2. Upgrade.

The current version of dalamud offered for Chinese server is 6.0.1.3 ...
The wondrous tails solver still worked fine several days ago for me and my friends.

**Comment by daemitus** [comment]
https://github.com/daemitus/WondrousTailsSolver/releases/tag/dalamud-6.0.1.3-CN

You can install this as a dev plugin, however you'll likely want to poke
bluefissure to pull in the latest Dalamud changes when they can.

**Comment by ha-ku** [comment]
Thanks a lot for helping!
