### ISSUE TITLE
Math shows 3-line as possible when it isn't

### ISSUE THREAD

**Issue by shaver** [MidoriKami/EzWondrousTails#5]
I'm at 8/9 and there's no way to get a 3-line result, but the plugin still shows 2.78% chance.
![ffxiv_dx11_2022-07-20_14-29-40](https://user-images.githubusercontent.com/416857/180056375-c3f34124-01cc-4e68-92f3-688706720215.png)

(Assuming that each location is equal odds, the calculation for 2-line is also off, since it should be 12.5% (one in eight).)

**Comment by daemitus** [comment]
iirc, it stops calculating after 7 stickers and just leaves what's present
there.
